<?php
$lang['home_maintext']      = "الجيل الجديد من نظام elementary OS وصل. خفيفة وجميلة. وكل التطبيقات الجديدة بشكل جديد. ضع السعر أو قم بتحميله مجانا.";
$lang['home_download']      = "تحميل";
$lang['home_payment']       = "دفع";
$lang['home_amount']        = "المبلغ";  // Amount of money
$lang['home_method']        = "وسيلة الدفع";  // Method of payment
$lang['home_processor']     = "العملية";//Processor 
$lang['home_creditcard']    = "بطاقة الائتمان";
$lang['home_direct']        = "مباشر"; // Direct download (via HTTP)
$lang['home_luna_free']     = "تحميل لونا مجانا";
$lang['home_elementary_is'] = "elementary is:";
$lang['home_point1']        = "Community Driven.";
$lang['home_expl1']         = "elementary لديه هدف واحد: هو توفير أفضل تجربة ممكنة لمجتمعنا. تقودنا الرغبة في أن نكون الأفضل، ليس بفضل الراتب. فالمساهمون لا يهدفون إلى تحقيق الربح الأقصى، بل إلى تحقيق الغرض الأقصى.";
$lang['home_point2']        = "شفاف ومفتوح.";
$lang['home_expl2']         = "نحن نؤمن بقوة المصادر المفتوحة والتعاون العالمي. هذا يعني أن أي شخص يمكنه تحميل واستخدام وتعديل والمساهمة في الكود الذي نكتبه لتحقيق أفكاره في الحياة. حيث الكود مفتوح للجميع، وهذا يعني أنه متاحة للمراجعة والتدقيق والتحسين من طرف عشرات الآلاف من المطورين في جميع أنحاء العالم. حتى يصل إلى نظامك.";
$lang['home_point3']        = "جميلة و سهلة الاستعمال.";
$lang['home_expl3']         = "elementary أنشئت بواسطة مصممين ومطورين يؤمنون بأن الحواسيب قد تكون سهلة وممتعة. بجعل التصميم أولا، مع ضمان أننا لا نساوم في الجودة أو سهولة الإستخدام.";
$lang['home_point4']        = "الحوسبة الحديثة.";
$lang['home_expl4']         = "elementary OS هو بديل مجاني لأنظمة Windows  و OS X . حيث يأتي بما قد لا تتوقعه مثل التصفح السريع للويب ومتجر لتطبيقات يحتوي على الألاف منها. إضافة إلى التحديثات المجانية وعدم تواجد الفيروسات.";
$lang['home_point5']        = "سريع";
$lang['home_expl5']         = "وقد تم تصميم لونا من الألف إلى الياء ليكون الضوء على أصابع القدم. حيث يبدأ بسرعة، بتسجيل الدخول على الفور، ويستخدم الحد الأدنى من الموارد بحيث تطبيقاتك تتمتع بسرعة كبيرة أيضا. ومع لونا، يمكنك الحصول على نفس الأساس الذي اختاره لينكس أسرع الحواسيب العملاقة في العالم.";
$lang['home_point6']        = "كامل المميزات";
$lang['home_expl6']         = "عند تثبيت elementary، أنت لم تقم بمجرد تثبيت نظام التشغيل. بل أنت تثبت جناح ممتاز مصمم خصيصا للتطبيقات التي تتيح لك الحصول على تصفح سريع وسهل على شبكة الإنترنت و التحقق من بريدك الالكتروني، والاستماع إلى الموسيقى، ومعالجة المهام اليومية .";
$lang['home_app1']          = "تصفح حسب الألبومات، انشئ قوائم التشغيل، وقيم الأغاني، وتعرف على موسيقى مشابهة.";
$lang['home_app2']          = "Surf the web with the speed of the same rendering engine as Google Chrome and Apple Safari.";
$lang['home_app3']          = "Connect with Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! and more.";
$lang['home_app4']          = "View multiple accounts, get desktop notifications, and read your mail in conversations.";
$lang['home_app5']          = "Import, Organize, and Edit photos. Make a slideshow. Share with Facebook or Flickr.";
$lang['home_app6']          = "Always stay on the cutting edge. Get updates right away, forever, for free.";
$lang['home_point7']        = "Fully Accessible";
$lang['home_expl7']         = "Different kinds of people from all over the world build elementary, so it’s no surprise that Luna is built with this in mind. It comes stocked with apps and tweaks for the hearing and sight impaired, as well as assistance for the motor impaired.";
$lang['home_point8']        = "Safe and Secure";
$lang['home_expl8']         = "Luna is built on the rock-solid foundation of Linux (the same software that powers the US Department of Defense, the Bank of China, and more). It has no known viruses, which means no pesky anti-virus software to slow down your system. Luna receives security updates as soon as a problem is discovered, meaning there’s no waiting around for the most secure system.";
$lang['home_point9']        = "100% Free";
$lang['home_expl9']         = "elementary OS is completely free, both in terms of pricing and licensing. There are no costly fees, confusing user agreements, trial periods, or restrictive copy protections. You can install Luna on as many computers as you want or even copy it and give it away to your friends.";
$lang['home_point10']       = "Ready for Apps";
$lang['home_expl10']        = "elementary OS comes with a built-in app store, stocked with thousands of free apps. Quickly find what you’re looking for without worrying about malware from the web.";
$lang['home_whatis']        = "What is"; // Whole sentence reads "what is elementary OS?"